# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  # baseURL: 'https://damlaendre.github.io/sepsi/en'
  languageCode: en-us
  contentDir: content/en/
  title: Damla & Endre
  params:
    description: ðŸ‘‹ Welcome to our wedding website! ðŸ‘‹
#  menu:
#    main:
#      - name: Home
#        url: /#top
#        weight: 10
#      - name: RSVP
#        url: https://forms.gle/2Eq7oZhvQa5VHxc87/
#        weight: 20
#      - name: Schedule
#        url: /#schedule
#        weight: 30
#      - name: Venue
#        url: /#venue
#        weight: 40
#      - name: Accommodation
#        url: /#accommodation
#        weight: 50
#      - name: Transportation
#        url: travel/
#        weight: 60
#      - name: Contact
#        url: /#contact
#        weight: 70
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
hu:
  languageCode: hu
  contentDir: content/hu
  title: Damla & Endre
  params:
    description: ðŸ‘‹ ÃœdvÃ¶zlÃ¼nk eskÅ±vÅ‘i honlapunkon! ðŸ‘‹
  #menu:
#main:
#- name: FÅ‘oldal
#url: /#top
#weight: 10
#- name: RÃ©szvÃ©tel
#url: https://forms.gle/SU54TxtCUmC9obbq8
#weight: 20
#- name: Program
#url: /#schedule
#weight: 30
#- name: HelyszÃ­n
#url: /#venue
#weight: 40
#- name: SzÃ¡llÃ¡shely
#url: /#accommodation
#weight: 50
#- name: ElÃ©rhetÅ‘sÃ©g
#url: /#contact
#weight: 70
