# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Főoldal
    url: /#top
    weight: 10
  - name: Részvétel
    url: https://forms.gle/SU54TxtCUmC9obbq8
    weight: 20
  - name: Program
    url: /#schedule
    weight: 30
  - name: Helyszín
    url: /#venue
    weight: 40
  - name: Szálláshely
    url: /#accommodation
    weight: 50
  - name: Elérhetőség
    url: /#contact
    weight: 70
    